/**
 * The client's legal pages, word for word as published on their current site
 * (captured 2026-09-24; structure read from the live pages 2026-09-25).
 * Update here when the client revises them; nothing else holds this copy.
 */
/**
 * A block of the client's words, unchanged. `strong` and `links` carry their page's own emphasis and links:
 * phrases of `text` to set in bold, or to link (an app path, or a mail address). A `signoff` closes a page.
 */
export type PolicyBlock = { kind: "heading" | "paragraph" | "item" | "signoff"; text: string; strong?: string[]; links?: [phrase: string, href: string][] };
export type Policy = { path: string; title: string; updated: string; standfirst?: string; blocks: PolicyBlock[] };

export const policies: Policy[] = [
  {
    path: "/terms",
    title: "Terms & Conditions",
    updated: "September 18, 2026",
    blocks: [
      { kind: "paragraph", text: "Welcome to TRUEMARK Biolabs. These Terms & Conditions govern your access to and use of the TRUEMARK Biolabs website, products, services, and customer account. By accessing this website or creating an account, you agree to be bound by these Terms & Conditions." },
      { kind: "paragraph", text: "If you do not agree with any part of these terms, please do not use this website or place an order." },
      { kind: "heading", text: "1. Eligibility" },
      { kind: "paragraph", text: "You must be at least 21 years old to create an account or purchase products from TRUEMARK Biolabs." },
      { kind: "paragraph", text: "By creating an account, you confirm that the information you provide is accurate and that you are legally permitted to purchase and receive research compounds in your jurisdiction." },
      { kind: "heading", text: "2. Research Use Only" },
      { kind: "paragraph", text: "All products offered by TRUEMARK Biolabs are sold strictly for laboratory research and analytical purposes only.", strong: ["strictly for laboratory research and analytical purposes only"] },
      { kind: "paragraph", text: "Our products are not intended for human consumption, veterinary use, diagnostic purposes, therapeutic use, or the treatment, prevention, or cure of any disease or medical condition.", strong: ["not intended for human consumption, veterinary use, diagnostic purposes, therapeutic use, or the treatment, prevention, or cure of any disease or medical condition"] },
      { kind: "paragraph", text: "Customers are responsible for ensuring that all products are used in accordance with applicable laws, regulations, laboratory standards, and safety requirements." },
      { kind: "paragraph", text: "TRUEMARK Biolabs does not authorize or recommend the use of its products in humans or animals." },
      { kind: "heading", text: "3. Product Information" },
      { kind: "paragraph", text: "We make reasonable efforts to ensure that product descriptions, specifications, availability, pricing, and other information displayed on the website are accurate and current." },
      { kind: "paragraph", text: "However, information may occasionally contain errors or omissions. TRUEMARK Biolabs reserves the right to correct errors, update information, change product specifications, or modify availability without prior notice." },
      { kind: "paragraph", text: "Product images are provided for identification and informational purposes and may not always represent the exact packaging or appearance of the product supplied." },
      { kind: "heading", text: "4. Certificates of Analysis and Lot Information" },
      { kind: "paragraph", text: "Where applicable, product lot information and Certificates of Analysis (CoAs) may be provided to registered customers." },
      { kind: "paragraph", text: "Customers should review the applicable lot information and documentation before using any product for laboratory research." },
      { kind: "paragraph", text: "The availability of a CoA does not change the intended use of the product or constitute a recommendation for human or veterinary use." },
      { kind: "heading", text: "5. Accounts" },
      { kind: "paragraph", text: "Certain website features, including product information, pricing, lot verification, certificates, and ordering functionality, may require a registered account." },
      { kind: "paragraph", text: "You are responsible for:" },
      { kind: "item", text: "Providing accurate and complete account information." },
      { kind: "item", text: "Maintaining the confidentiality of your login credentials." },
      { kind: "item", text: "Keeping your account information up to date." },
      { kind: "item", text: "Not sharing your account credentials with unauthorized individuals." },
      { kind: "item", text: "Not using another person’s account without authorization." },
      { kind: "paragraph", text: "You are responsible for all activity conducted through your account." },
      { kind: "paragraph", text: "TRUEMARK Biolabs reserves the right to suspend or terminate an account if we believe the account is being used in violation of these Terms & Conditions or applicable law." },
      { kind: "heading", text: "6. Orders and Acceptance" },
      { kind: "paragraph", text: "Submitting an order constitutes a request to purchase products and does not necessarily constitute acceptance of the order." },
      { kind: "paragraph", text: "TRUEMARK Biolabs reserves the right to accept, reject, limit, or cancel any order at our discretion, including where there are concerns regarding product availability, payment, shipping restrictions, eligibility, or compliance with applicable laws." },
      { kind: "paragraph", text: "If an order is cancelled after payment has been received, any applicable refund will be processed according to our refund and cancellation policies." },
      { kind: "heading", text: "7. Pricing and Payment" },
      { kind: "paragraph", text: "All prices displayed on the website are subject to change without notice." },
      { kind: "paragraph", text: "You agree to provide valid and accurate payment and billing information when placing an order." },
      { kind: "paragraph", text: "TRUEMARK Biolabs reserves the right to correct pricing errors and cancel orders affected by incorrect pricing." },
      { kind: "paragraph", text: "You are responsible for any applicable taxes, duties, customs charges, or other fees associated with your purchase unless otherwise stated." },
      { kind: "heading", text: "8. Shipping and Delivery" },
      { kind: "paragraph", text: "Customers are responsible for providing accurate shipping information." },
      { kind: "paragraph", text: "TRUEMARK Biolabs is not responsible for delays or delivery failures caused by incorrect addresses, carrier delays, customs procedures, government restrictions, or circumstances beyond our reasonable control." },
      { kind: "paragraph", text: "Customers are responsible for ensuring that the purchase and shipment of research compounds are permitted under the laws and regulations applicable to their location." },
      { kind: "heading", text: "9. Returns, Refunds, and Cancellations" },
      { kind: "paragraph", text: "Returns, refunds, and order cancellations are subject to TRUEMARK Biolabs’ applicable refund policy." },
      { kind: "paragraph", text: "Due to the nature of laboratory research products, certain products may not be eligible for return once shipped or opened." },
      { kind: "paragraph", text: "Customers should contact TRUEMARK Biolabs as soon as possible if an order arrives damaged, incorrect, or incomplete." },
      { kind: "paragraph", text: "Any approved refund will be issued using the original payment method where reasonably possible." },
      { kind: "heading", text: "10. Prohibited Uses" },
      { kind: "paragraph", text: "You agree not to use TRUEMARK Biolabs products, website, or services for any unlawful purpose." },
      { kind: "paragraph", text: "You must not:" },
      { kind: "item", text: "Use products for human or veterinary administration." },
      { kind: "item", text: "Misrepresent the intended use of products." },
      { kind: "item", text: "Resell products in violation of applicable laws or restrictions." },
      { kind: "item", text: "Use the website to conduct fraudulent or unauthorized activity." },
      { kind: "item", text: "Attempt to gain unauthorized access to accounts, systems, or website functionality." },
      { kind: "item", text: "Use the website in a manner that could damage, disable, or impair its operation." },
      { kind: "heading", text: "11. Intellectual Property" },
      { kind: "paragraph", text: "All content on this website, including text, graphics, logos, images, product information, designs, trademarks, software, and other materials, is owned by or licensed to TRUEMARK Biolabs unless otherwise stated." },
      { kind: "paragraph", text: "You may not reproduce, distribute, modify, copy, publish, or commercially exploit website content without prior written permission." },
      { kind: "heading", text: "12. Disclaimer of Warranties" },
      { kind: "paragraph", text: "To the extent permitted by applicable law, the website and its content are provided on an “as is” and “as available” basis." },
      { kind: "paragraph", text: "TRUEMARK Biolabs does not guarantee that the website will always be available, uninterrupted, secure, or error-free." },
      { kind: "paragraph", text: "Nothing on this website should be interpreted as medical, pharmaceutical, clinical, or veterinary advice." },
      { kind: "heading", text: "13. Changes to These Terms" },
      { kind: "paragraph", text: "TRUEMARK Biolabs may update or modify these Terms & Conditions from time to time." },
      { kind: "paragraph", text: "Any changes will become effective when the updated terms are published on this website. Your continued use of the website after changes are posted constitutes acceptance of the updated Terms & Conditions." },
      { kind: "heading", text: "14. Governing Law" },
      { kind: "paragraph", text: "These Terms & Conditions shall be governed by and interpreted in accordance with the applicable laws of the jurisdiction in which TRUEMARK Biolabs operates, without regard to conflict-of-law principles." },
      { kind: "paragraph", text: "Any disputes arising from these Terms & Conditions or your use of the website shall be handled in accordance with applicable law." },
      { kind: "heading", text: "14. Contact Us" },
      { kind: "paragraph", text: "If you have questions about these Terms & Conditions, please contact TRUEMARK Biolabs through the contact information provided on our website." },
      { kind: "signoff", text: "TRUEMARK Biolabs Research compounds, verified by lot.", strong: ["TRUEMARK Biolabs"] },
    ],
  },
  {
    path: "/privacy-policy",
    title: "Privacy policy",
    updated: "September 18, 2026",
    standfirst: "How TrueMark collects, uses, and protects the information you share with us across our site, lot-verification tool, and orders.",
    blocks: [
      { kind: "paragraph", text: "This Privacy Policy explains how TrueMark (“TrueMark,” “we,” “us,” or “our”) collects, uses, discloses, and safeguards information when you visit our website, create an account, place an order, or use our lot-verification tool to look up a Certificate of Analysis. By using our site, you agree to the practices described in this policy. Our products are sold strictly for research use only and are not intended for human or animal consumption; this policy covers data privacy only and does not amend our Terms of Sale." },
      { kind: "heading", text: "Information We Collect" },
      { kind: "paragraph", strong: ["Account & order information."], text: "Account & order information. When you create an account or place an order, we collect your name, email address, shipping and billing address, phone number, and payment details (processed securely by our payment provider — we do not store full card numbers on our servers)." },
      { kind: "paragraph", strong: ["Lot verification data."], text: "Lot verification data. When you enter a lot number on our Verify page, we log the lot number, timestamp, and general location of the request to detect misuse and to improve the tool. We do not require an account to use lot verification." },
      { kind: "paragraph", strong: ["Usage data."], text: "Usage data. We automatically collect information about your device, browser, IP address, pages viewed, and referring URLs through cookies and similar technologies, as described below." },
      { kind: "paragraph", strong: ["Communications."], text: "Communications. If you contact us through our contact form or email, we retain the content of that message and our replies to provide support and keep a record of the correspondence." },
      { kind: "heading", text: "How We Use Your Information" },
      { kind: "paragraph", text: "We use the information we collect to:" },
      { kind: "item", text: "Process, fulfil, and ship your orders, and send order and shipping confirmations." },
      { kind: "item", text: "Create and maintain your account, including order history and saved addresses." },
      { kind: "item", text: "Respond to lot-verification requests and return the correct Certificate of Analysis." },
      { kind: "item", text: "Respond to customer service and support enquiries." },
      { kind: "item", text: "Detect, investigate, and prevent fraud, abuse, and security incidents." },
      { kind: "item", text: "Improve our website, products, and the accuracy of our verification tool." },
      { kind: "item", text: "Send transactional emails and, where you have opted in, occasional product or compliance updates." },
      { kind: "item", text: "Comply with legal, tax, and regulatory obligations." },
      { kind: "heading", text: "Cookies & Tracking Technologies" },
      { kind: "paragraph", text: "We use cookies and similar technologies to keep you signed in, remember items in your cart, understand how visitors use our site, and measure the performance of our pages. You can control or disable cookies through your browser settings; doing so may affect features such as cart persistence and sign-in." },
      { kind: "paragraph", text: "We may use privacy-respecting analytics tools to understand aggregate site traffic. We do not sell your personal information to third-party advertisers." },
      { kind: "heading", text: "How We Share Your Information" },
      { kind: "paragraph", text: "We do not sell your personal information. We share information only as needed to run our business:" },
      { kind: "item", strong: ["Service providers"], text: "Service providers — payment processors, shipping carriers, email delivery services, and website hosting providers, each bound by confidentiality and data-protection obligations." },
      { kind: "item", strong: ["Legal & safety"], text: "Legal & safety — where required to comply with a law, regulation, subpoena, or to protect the rights, property, or safety of TrueMark, our customers, or others." },
      { kind: "item", strong: ["Business transfers"], text: "Business transfers — in connection with a merger, acquisition, or sale of assets, subject to this policy continuing to apply to your information." },
      { kind: "heading", text: "Data Retention" },
      { kind: "paragraph", text: "We retain account and order information for as long as your account is active and as needed to meet accounting, tax, and legal record-keeping requirements. Lot-verification logs are retained for a limited period to support fraud detection and are periodically purged. You may request earlier deletion as described under “Your Rights” below, subject to any legal retention obligations." },
      { kind: "heading", text: "Data Security" },
      { kind: "paragraph", text: "We use industry-standard technical and organizational measures — including encrypted connections (HTTPS), access controls, and secure payment processing — to protect your information. No method of transmission or storage is completely secure, and we cannot guarantee absolute security." },
      { kind: "heading", text: "Your Rights & Choices" },
      { kind: "paragraph", text: "Depending on where you live, you may have the right to access, correct, export, or delete the personal information we hold about you, and to opt out of marketing communications at any time using the unsubscribe link in any email. To exercise these rights, contact us using the details below; we will respond within a reasonable timeframe and may need to verify your identity first." },
      { kind: "heading", text: "Children’s Privacy" },
      { kind: "paragraph", text: "Our site and products are intended for research professionals and are not directed to individuals under 18. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us and we will delete it." },
      { kind: "heading", text: "Third-Party Links" },
      { kind: "paragraph", text: "Our website may link to third-party sites, including carrier tracking pages and payment providers. We are not responsible for the privacy practices of those third parties, and we encourage you to review their policies separately." },
      { kind: "heading", text: "Changes to This Policy" },
      { kind: "paragraph", text: "We may update this Privacy Policy from time to time to reflect changes in our practices or for legal reasons. We will post the revised policy on this page with an updated “Last updated” date, and, for material changes, provide a more prominent notice." },
      { kind: "heading", text: "Contact Us" },
      { kind: "paragraph", text: "If you have questions about this Privacy Policy or how we handle your information, contact us at privacy@truemark.com or through our Contact page.", links: [["privacy@truemark.com", "mailto:privacy@truemark.com"], ["Contact page", "/contact"]] },
    ],
  },
  {
    path: "/refund_returns",
    title: "Refund and Returns Policy",
    updated: "September 18, 2026",
    blocks: [
      { kind: "paragraph", text: "At TRUEMARK Biolabs, we are committed to providing high-quality research products. Due to the nature of our products, all sales are subject to the following policy." },
      { kind: "heading", text: "1. General Policy" },
      { kind: "paragraph", text: "At TRUEMARK Biolabs, we aim to provide high-quality research products. Due to the nature of our products, returns and refunds are subject to the conditions outlined below." },
      { kind: "heading", text: "2. Eligible Returns" },
      { kind: "paragraph", text: "We accept returns only for products that arrive damaged, defective, or incorrect." },
      { kind: "heading", text: "3. Return Period" },
      { kind: "paragraph", text: "Return requests must be submitted within 7 days of delivery. Please include your order number and clear photos of the product and packaging.", strong: ["7 days of delivery"] },
      { kind: "heading", text: "4. Condition of Products" },
      { kind: "paragraph", text: "Returned products must remain unopened and in their original condition. Opened, used, altered, or improperly stored products are not eligible for return." },
      { kind: "heading", text: "5. Damaged or Incorrect Orders" },
      { kind: "paragraph", text: "If you receive a damaged or incorrect product, please contact us promptly so we can review the issue and determine the appropriate resolution." },
      { kind: "heading", text: "6. Refunds" },
      { kind: "paragraph", text: "Once an approved return has been received and inspected, we will notify you regarding the refund. Approved refunds will be issued to the original payment method." },
      { kind: "heading", text: "7. Shipping Costs" },
      { kind: "paragraph", text: "Original shipping costs are generally non-refundable. If the return is due to an error on our part, we may cover the applicable return shipping costs." },
      { kind: "heading", text: "8. Order Cancellations" },
      { kind: "paragraph", text: "Cancellation requests must be submitted before an order is shipped. Once an order has shipped, cancellation may no longer be possible." },
      { kind: "heading", text: "9. Refund Processing" },
      { kind: "paragraph", text: "Refund processing times may vary depending on your payment provider or financial institution. TRUEMARK Biolabs is not responsible for delays caused by third-party payment processors." },
      { kind: "heading", text: "10. Contact Us" },
      { kind: "paragraph", text: "For questions regarding returns, refunds, or cancellations, please contact TRUEMARK Biolabs through the contact information provided on our website." },
      { kind: "signoff", text: "TRUEMARK Biolabs", strong: ["TRUEMARK Biolabs"] },
    ],
  },
  {
    path: "/shipping-policy",
    title: "Shipping Policy",
    updated: "September 18, 2026",
    blocks: [
      { kind: "heading", text: "1. Shipping Overview" },
      { kind: "paragraph", text: "TRUEMARK Biolabs ships research products to eligible locations where the purchase and shipment of such products are permitted by applicable laws and regulations." },
      { kind: "heading", text: "2. Order Processing" },
      { kind: "paragraph", text: "Orders are typically processed within 1–3 business days after payment is confirmed. Processing times may vary depending on order volume and product availability.", strong: ["1–3 business days"] },
      { kind: "heading", text: "3. Shipping Methods" },
      { kind: "paragraph", text: "Available shipping options and estimated delivery times will be displayed during checkout. Delivery times are estimates and are not guaranteed." },
      { kind: "heading", text: "4. Shipping Address" },
      { kind: "paragraph", text: "Customers are responsible for providing accurate and complete shipping information. We are not responsible for delays or failed deliveries caused by incorrect or incomplete addresses." },
      { kind: "heading", text: "5. Tracking Information" },
      { kind: "paragraph", text: "When available, tracking information will be provided once your order has been shipped. Customers can use the tracking information to monitor delivery status." },
      { kind: "heading", text: "6. Shipping Delays" },
      { kind: "paragraph", text: "Delivery may be delayed due to carrier issues, weather, customs processing, holidays, or circumstances beyond our control." },
      { kind: "heading", text: "7. Customs and Import Requirements" },
      { kind: "paragraph", text: "Customers are responsible for understanding and complying with all applicable local laws, import requirements, duties, taxes, and customs regulations." },
      { kind: "heading", text: "8. Undeliverable Packages" },
      { kind: "paragraph", text: "Packages returned to us due to an incorrect address, refusal, or failure to receive the shipment may be subject to additional shipping charges before reshipment." },
      { kind: "heading", text: "9. Lost or Damaged Shipments" },
      { kind: "paragraph", text: "If your order arrives damaged or appears to be lost in transit, please contact us as soon as possible with your order and tracking information so we can assist with the issue." },
      { kind: "heading", text: "10. Contact Us" },
      { kind: "paragraph", text: "For questions regarding shipping or delivery, please contact TRUEMARK Biolabs through the contact information provided on our website." },
      { kind: "signoff", text: "TRUEMARK Biolabs", strong: ["TRUEMARK Biolabs"] },
    ],
  },
];

export const policyByPath = (path: string) => policies.find((p) => p.path === path);
