-- Generated by node scripts/gen-live-seed.mjs. Do not edit by hand.
-- Sources: src/data.ts products; src/platform/seed.ts shippingMethods.
-- Insert missing records only: reruns preserve the client's prices, releases,
-- inventory and promo decisions. No fictional people, orders, partners or results.
begin;
set local standard_conforming_strings = on;

insert into public.products (id, name, size, category, price, image, color, color_ink, form, lot, tag, active) values
  ('retatrutide-10-mg', 'Retatrutide', '10 mg', 'peptide-fragments', 50, '/images/products/retatrutide-10-mg.png', '#7A39B1', '#471C6C', 'Lyophilized powder', 'TM-RET10-2609-01', null, true),
  ('retatrutide-20-mg', 'Retatrutide', '20 mg', 'peptide-fragments', 80, '/images/products/retatrutide-20-mg.png', '#7A39B1', '#471C6C', 'Lyophilized powder', 'TM-RET20-2609-01', null, true),
  ('retatrutide-30-mg', 'Retatrutide', '30 mg', 'peptide-fragments', 100, '/images/products/retatrutide-30-mg.png', '#7A39B1', '#471C6C', 'Lyophilized powder', 'TM-RET30-2609-01', null, true),
  ('retatrutide-60-mg', 'Retatrutide', '60 mg', 'peptide-fragments', 155, '/images/products/retatrutide-60-mg.png', '#7A39B1', '#471C6C', 'Lyophilized powder', 'TM-RET60-2609-01', null, true),
  ('tirzepatide-30-mg', 'Tirzepatide', '30 mg', 'peptide-fragments', 70, '/images/products/tirzepatide-30-mg.png', '#7A39B1', '#471C6C', 'Lyophilized powder', 'TM-TRZ30-2609-01', null, true),
  ('semaglutide-20-mg', 'Semaglutide', '20 mg', 'peptide-fragments', 45, '/images/products/semaglutide-20-mg.png', '#7A39B1', '#471C6C', 'Lyophilized powder', 'TM-SEM20-2609-01', null, true),
  ('cagrilintide-10-mg', 'Cagrilintide', '10 mg', 'peptide-fragments', 70, '/images/products/cagrilintide-10-mg.png', '#7A39B1', '#471C6C', 'Lyophilized powder', 'TM-CAG10-2609-01', null, true),
  ('bpc-157-10-mg', 'BPC-157', '10 mg', 'peptide-fragments', 40, '/images/products/bpc-157-10-mg.png', '#058F93', '#005658', 'Lyophilized powder', 'TM-BPC10-2609-01', 'Best seller', true),
  ('bpc-tb-1010-mg', 'BPC-157 / TB-500', '10 mg / 10 mg', 'peptide-fragments', 80, '/images/products/bpc-157-tb-500-10-mg-10-mg.png', '#058F93', '#005658', 'Lyophilized powder', 'TM-BTB10-2609-01', null, true),
  ('kpv-10-mg', 'KPV', '10 mg', 'peptide-fragments', 40, '/images/products/kpv-10-mg.png', '#058F93', '#005658', 'Lyophilized powder', 'TM-KPV10-2609-01', null, true),
  ('ghk-cu-100-mg', 'GHK-Cu', '100 mg', 'copper-complexes', 40, '/images/products/ghk-cu-100-mg.png', '#CC3358', '#7C1830', 'Lyophilized powder', 'TM-GHK100-2609-01', null, true),
  ('glow-70-mg', 'GLOW', '70 mg', 'peptide-fragments', 75, '/images/products/glow-70-mg.png', '#CC3358', '#7C1830', 'Lyophilized powder', 'TM-GLW70-2609-01', 'New', true),
  ('tesamorelin-10-mg', 'Tesamorelin', '10 mg', 'secretagogue-peptides', 75, '/images/products/tesamorelin-10-mg.png', '#0273D0', '#00437A', 'Lyophilized powder', 'TM-TES10-2609-01', null, true),
  ('nad-500-mg', 'NAD+', '500 mg', 'amino-acids', 55, '/images/products/nad-plus-500-mg.png', '#B97102', '#6C4200', 'Lyophilized powder', 'TM-NAD500-2609-01', null, true),
  ('mots-c-10-mg', 'MOTS-C', '10 mg', 'mitochondrial-peptides', 50, '/images/products/mots-c-10-mg.png', '#B97102', '#6C4200', 'Lyophilized powder', 'TM-MOT10-2609-01', null, true),
  ('semax-10-mg', 'Semax', '10 mg', 'neuropeptides', 40, '/images/products/semax-10-mg.png', '#4E762E', '#2D4817', 'Lyophilized powder', 'TM-SMX10-2609-01', null, true),
  ('selank-10-mg', 'Selank', '10 mg', 'neuropeptides', 40, '/images/products/selank-10-mg.png', '#4E762E', '#2D4817', 'Lyophilized powder', 'TM-SLK10-2609-01', null, true),
  ('melanotan-ii-10-mg', 'Melanotan II', '10 mg', 'melanocortin-analogs', 40, '/images/products/melanotan-ii-10-mg.png', '#AB531A', '#682F0B', 'Lyophilized powder', 'TM-MEL10-2609-01', null, true),
  ('bacteriostatic-water-10-ml', 'BAC Water', '10 mL', 'lab-supplies', 10, '/images/products/bac-water-10-ml.png', '#486377', '#253A49', 'Research diluent', 'TM-BAC10-2609-01', null, true),
  ('cjc-ipa-1010-mg', 'CJC (No DAC) / Ipamorelin', '10 mg / 10 mg', 'secretagogue-peptides', 55, '/images/products/cjc-no-dac-ipamorelin-10-mg-10-mg.png', '#0273D0', '#00437A', 'Lyophilized powder', 'TM-CJI10-2609-01', null, true)
on conflict (id) do nothing;

-- Only the identifiers are established facts. Dates and stock counts in the
-- preview are generated, so received_at and units deliberately remain null.
insert into public.lots (lot, product_id, status, results) values
  ('TM-RET10-2609-01', 'retatrutide-10-mg', 'testing', '[]'),
  ('TM-RET20-2609-01', 'retatrutide-20-mg', 'testing', '[]'),
  ('TM-RET30-2609-01', 'retatrutide-30-mg', 'testing', '[]'),
  ('TM-RET60-2609-01', 'retatrutide-60-mg', 'testing', '[]'),
  ('TM-TRZ30-2609-01', 'tirzepatide-30-mg', 'testing', '[]'),
  ('TM-SEM20-2609-01', 'semaglutide-20-mg', 'testing', '[]'),
  ('TM-CAG10-2609-01', 'cagrilintide-10-mg', 'testing', '[]'),
  ('TM-BPC10-2609-01', 'bpc-157-10-mg', 'testing', '[]'),
  ('TM-BTB10-2609-01', 'bpc-tb-1010-mg', 'testing', '[]'),
  ('TM-KPV10-2609-01', 'kpv-10-mg', 'testing', '[]'),
  ('TM-GHK100-2609-01', 'ghk-cu-100-mg', 'testing', '[]'),
  ('TM-GLW70-2609-01', 'glow-70-mg', 'testing', '[]'),
  ('TM-TES10-2609-01', 'tesamorelin-10-mg', 'testing', '[]'),
  ('TM-NAD500-2609-01', 'nad-500-mg', 'testing', '[]'),
  ('TM-MOT10-2609-01', 'mots-c-10-mg', 'testing', '[]'),
  ('TM-SMX10-2609-01', 'semax-10-mg', 'testing', '[]'),
  ('TM-SLK10-2609-01', 'selank-10-mg', 'testing', '[]'),
  ('TM-MEL10-2609-01', 'melanotan-ii-10-mg', 'testing', '[]'),
  ('TM-BAC10-2609-01', 'bacteriostatic-water-10-ml', 'testing', '[]'),
  ('TM-CJI10-2609-01', 'cjc-ipa-1010-mg', 'testing', '[]')
on conflict (lot) do nothing;

insert into public.shipping_methods (id, label, detail, price, active) values
  ('cold-2day', 'Cold chain · 2 business days', 'Shipped with temperature control', 24, true),
  ('cold-overnight', 'Cold chain · overnight', 'Shipped with temperature control, next business day', 42, true)
on conflict (id) do nothing;

-- Sample offer percentages are retained but disabled until the client decides.
insert into public.discounts (code, kind, percent, active) values
  ('FIRSTLOT', 'promo', 10, false),
  ('WELCOME5', 'promo', 5, false)
on conflict (code) do nothing;

commit;
